### ISSUE TITLE
this is yours

### ISSUE THREAD

**Issue by tinruufu** [CyangrassInnovations/CyanDate#4]
im not going to encourage you to disobey your parents if you don't _want_ to, but your parents don't own everything you make just because you're under 18 and can't stop you licensing your stuff how you please. if you're obeying out of choice or whatever, that's fine, but the way your readme is written makes me suspect you'd rather this was MIT or GPL or w/e

awesome project btw, i've filed a feedback bug with apple about how hard it is to find the date in ios 10, and this is a wonderful workaround for the issue if it remains

**Comment by cyanisaac** [comment]
I would prefer to put the app under the MIT license. However, long story short, it would be an ordeal to put it under that license. My parents do not want someone using the code for commercial purposes. While I think it would never get approved/work out for someone who's stealing code, it's not up to me it's up to my parents.

The project can either stay up under noncommercial or it can go down entirely, and I'd prefer to keep it up. My parents cannot restrict me to licenses but he can force me to take down my GitHub. As well, I personally do not like the GPL license and I do not wish to use it in my projects. 

If you want to use snippets of code, or want to use it as a learning resource for how to work with dates, I will not stop you. The license is there to keep people from "stealing" the project while allowing people to contribute. For the time being, I'm keeping it under Creative Commons Attribution ShareAlike NonCommercial 4.0.

**Comment by cyanisaac** [comment]
Okay, I've decided to go ahead and license this under the MPLv2 instead of Creative Commons. I think this is a good idea for CyanDate as it isn't too restrictive, people can utilize this in their own projects but they have to disclose any changes they make which means it will benefit CyanDate.
